sequence containers : array ,vector ,deque ,lisy 
associative containers : set , map , multiset ,multimap
container adaptors stack ,queue,...
unordered associative containers: unordered_set unordered_map unordered_multiset ...